mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://ecommerce-auth.com
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=cart_db
quarkus.http.port=8083
quarkus.rest-client.product-api.url=${PRODUCT_API_URL:http://localhost:8082}
quarkus.rest-client.product-api.scope=jakarta.inject.Singleton
quarkus.swagger-ui.always-include=true
