mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://ecommerce-auth.com
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=order_db
quarkus.http.port=8084
quarkus.rest-client.cart-api.url=${CART_API_URL:http://localhost:8083}
quarkus.rest-client.cart-api.scope=jakarta.inject.Singleton
quarkus.rest-client.product-api.url=${PRODUCT_API_URL:http://localhost:8082}
quarkus.rest-client.product-api.scope=jakarta.inject.Singleton
quarkus.rest-client.notification-api.url=${NOTIFICATION_API_URL:http://localhost:8085}
quarkus.rest-client.notification-api.scope=jakarta.inject.Singleton
quarkus.swagger-ui.always-include=true
